version: '3.8'

services:
  kong-database:
    image: postgres:13  # Sử dụng PostgreSQL chính thức
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    volumes:
      - kong-database-data:/var/lib/postgresql/data
    networks:
      - kong-net
    restart: always

  kong:
    image: kong/kong-gateway:latest
    container_name: kong-service
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PORTAL=true
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8002
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8003
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"   # Cổng Proxy API
      - "8002:8002"   # Cổng Admin API
      - "8003:8003"   # Cổng Portal UI
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: always
  
  kong-migrations:
    image: kong/kong-gateway:latest
    container_name: kong-migrations-service
    command: kong migrations bootstrap
    profiles: [ "database" ]
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
    depends_on:
      - kong-database
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure

  kong-migrations-up:
    image: kong/kong-gateway:latest
    container_name: kong-migrations-up-service
    command: kong migrations up && kong migrations finish
    profiles: [ "database" ]
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
    depends_on:
      - kong-database
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure

volumes:
  kong-database-data:

networks:
  kong-net:
    driver: bridge
