version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8500:8080"
    environment:
      - SWAGGER_JSON=http://api:8000/swagger.json
    volumes:
      - ./swagger:/swagger
    restart: always