version: '3.8'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master-service
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-master-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-replica:
    image: redis:latest
    container_name: redis-replica-service
    ports:
      - "6380:6379"
    networks:
      - redis-network
    depends_on:
      - redis-master
    volumes:
      - redis-replica-data:/data
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight-service
    ports:
      - "8001:5540"
    networks:
      - redis-network
    depends_on:
      - redis-master

volumes:
  redis-master-data:
  redis-replica-data:

networks:
  redis-network:
    driver: bridge